### ISSUE TITLE
Enforce that compilers are single-use

### ISSUE THREAD

**Issue by ascopes** [ascopes/jct#18]
Add logic to enforce that compilers are single-use by implementing a flag that gets set after first use.

Throw a new type of exception if reuse is detected.

**Comment by adolfo-trocoli** [comment]
Could you be a bit more precise about that? I think i could help. What classes need to be modified?

**Comment by ascopes** [comment]
Hey! Sure thing!

This one is pretty simple. There just needs to be a boolean flag in SimpleCompiler that gets set when the `compile` call is made. An exception type that extends `CompilerException` can then be thrown when that boolean is already set and `compile` is called!

A couple of unit tests for the exception type itself and to ensure the call to `compile` throws if the flag is already set then should be good to make sure it works!

Sorry for the vague issues. Didn't expect anyone would spot this repo, so I kind of just left issues as notes to myself. I will go through and make sure everything is detailed correctly though.

Thanks for wanting to help out!

**Comment by adolfo-trocoli** [comment]
I've written some code and sent some pull requests. As I said, I'm just starting so I'm sorry if I've done something wrong, I haven't figured out how collaborating works. Also, I would love some feedback on my code even though it's very simple. Let me know what you think.

**Comment by ascopes** [comment]
Hey, all good! Might be worth keeping those together in a single pull request since they are all related, though :-) 

that way we can verify all the tests work before we merge it
